### ISSUE TITLE
No information on readme about participating

### ISSUE THREAD

**Issue by ghost** [EddieHubCommunity/Hackathons#35]
there's no information on readme about participating. It is kind of a bad experience for people willing to apply.

**Comment by kaiwalyakoparkar** [comment]
What kind of hackathons you want to participate in. Guild-based or team-based?

**Comment by ghost** [comment]
I don't know about anything related to it. I just came to this repo and there was no information. Thus, opened this issue (first asked on discord then @Rahma-AlWadhahi recommended to do so). So I don't know anything

**Comment by Rahma-AlWadhahi** [comment]
I think that it would be great to add some links to the previous Hackathon. For example, people have participated in Local Hack Day, why isn't there any link to that if it happens in different times? Like maybe having a link to the next possible date for the Hackathon to occur?
This way, we will show the people's work as well as get more potential participants in the next edition of the Hackathon whether it is Local Hack Day or any other Hackathon.

**Comment by kaiwalyakoparkar** [comment]
@Rahma-AlWadhahi You are right. So we can add previous hackathons and coming dates and timing to Share & build hackathons!

**Comment by ghost** [comment]
Closing this on @kaiwalyakoparkar's concern (🆙)
