### ISSUE TITLE
Suggestion for readme

### ISSUE THREAD

**Issue by Jassi10000-zz** [EddieHubCommunity/Hackathons#37]
I want to suggest an improvement in readme 
Can readme include all the upcoming hackathons category wise , so that it can become a one stop resource to follow for visitors?

Whatever hackathon the visitor wants to register writes his name in the respective folder , in this way many participants will be able to find team members for them

**Comment by Vyvy-vi** [comment]
This repo is much more of an archive of _past hackathons_, and what EddieHub's members made during those hackathons
