### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by duckstroms** [EddieHubCommunity/Hackathons#38]

**Comment by duckstroms** [comment]
.

**Comment by Vyvy-vi** [comment]
Hi, if you want to become a member of the org, you'll have to open an issue here-
https://github.com/EddieHubCommunity/support/issues/new?assignees=&labels=invite+me+to+the+organisation&template=invitation.md&title=Please+invite+me+to+the+GitHub+Community+Organization
