### ISSUE TITLE
Discussion on Images in the repo

### ISSUE THREAD

**Issue by Vyvy-vi** [EddieHubCommunity/Hackathons#6]
I think, eventually there might be a massive accumulation of images inside this repo.
Could we all discuss ways to deal with this problem beforehand?

Some solutions, that seem to work on this:
- running ImgBot on the repo
- making a github action, that turns images into img-links, after leveraging either an image-dump service, or a dedicated cloud server for the images. (or something that turns those images into embedded images, that are stored by github seperately)

**Comment by eddiejaoude** [comment]
Great topic, you are right, this could get big. I thought of using GitHub Issues and then using the generated urls - I wanted to see from 1 hackathon how much content was added. Then we will have a better idea of how to organise it all. Let's keep discussing

**Comment by schmelto** [comment]
ImgBot :+1:

**Comment by Vyvy-vi** [comment]
I think this is still needed stalebot
